services:
  postgres:
    image: postgres:18
    container_name: pg-view-migrator-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data: