-- auto_views.t_merchant_branch definition

-- Drop table

-- DROP TABLE auto_views.t_merchant_branch;

CREATE TABLE auto_views.t_merchant_branch (
	partner_id uuid NULL,
	partner_brand_id uuid NULL,
	partner_branch_id uuid NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	status varchar(255) NULL,
	governorate varchar(50) NULL,
	city varchar(50) NULL,
	area varchar(255) NULL,
	brand_name varchar(255) NULL,
	branch_name varchar(255) NULL,
	category text NULL,
	channel varchar(255) NULL,
	first_loan_date date NULL,
	last_loan_date date NULL,
	total_loans int8 NULL,
	running_loans int8 NULL,
	closed_loans int8 NULL,
	early_settled_loans int8 NULL,
	cancelled_loans int8 NULL,
	partial_refund_loans int8 NULL,
	total_consumers int8 NULL,
	repeat_consumers int8 NULL,
	repeat_consumer_rate_percent numeric NULL,
	total_paid_installments numeric NULL,
	total_remaining_installments numeric NULL,
	total_due_amount numeric NULL,
	total_due_paid_amount numeric NULL,
	overall_collection_rate numeric NULL,
	total_due_to_date numeric NULL,
	total_due_paid_to_date numeric NULL,
	collection_rate_to_date numeric NULL,
	total_principal_amount numeric NULL,
	total_principal_paid_amount numeric NULL,
	total_principal_to_date numeric NULL,
	total_principal_paid_to_date numeric NULL,
	total_interest_amount numeric NULL,
	total_interest_paid_amount numeric NULL,
	total_interest_to_date numeric NULL,
	total_interest_paid_to_date numeric NULL,
	interest_to_principal_ratio_percent numeric NULL,
	total_admin_fee_amount numeric NULL,
	avg_financed_amount numeric NULL,
	max_financed_amount numeric NULL,
	avg_tenor numeric NULL,
	has_new_loan_in_last_30_days bool NULL,
	checkout_success_rate numeric NULL,
	unpaid_installments_last_30_days numeric NULL,
	unpaid_installments_31_60_days numeric NULL,
	unpaid_installments_61_90_days numeric NULL,
	unpaid_installments_90_plus_days numeric NULL,
	last_refreshed_at timestamp NULL,
    test11 varchar
);